name: cypress parallel
on:
  push:
    branches: main
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Cypress
        uses: cypress-io/github-action@v5
        with:
          runTests: false
  tests:
    runs-on: ubuntu-latest
    needs: install
    strategy:
      fail-fast: false
      matrix:
        containers: [example1, example2]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Test Parallel
        uses: cypress-io/github-action@v5
        with:
          spec: cypress/e2e/${{matrix.containers}}.cy.js
          browser: chrome
